### ISSUE TITLE
game detection

### ISSUE THREAD

**Issue by BtencateSphereon** [urwrstkn8mare/gog-riot-integration#3]
Is there a chance this can be reworked?

For the plugin to detect any installed Riot games, they must be in your start menu shortcuts.

I don't have games in my start menu and i don't want them there :)

Maybe check the registry?

I just noticed the TODO, so you can close this if you want :)

**Comment by urwrstkn8mare** [comment]
Thanks for bringing this up. I know it is in the TODO but until Riot changes something I don't see any way of doing it without a start menu shortcut. I originally looked to the registry like the Minecraft plugin but Riot doesn't have anything there from what I saw. I left it in the TODO because I might end up finding a way or somebody else might. If they do I'd happily implement it in the plugin or accept a pull request. Until then, I'll leave the issue open anyway and update it If there are any updates related to this.

**Comment by BanCrash** [comment]
@urwrstkn8mare 

Maybe you can use the uninstall info in the registry:

HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Riot Game valorant.live

I guess if the Valorant is uninstalled, this entry will be deleted too. I didn't tested it though.

EDIT: This is only for Valorant, wich is the only game I have. I don't know if the others will appear there too.

**Comment by urwrstkn8mare** [comment]
@BanCrash Thanks for this. I'll definitely have a look at this. I'll update this issue with what I find.

**Comment by urwrstkn8mare** [comment]
I only have League and Valorant installed but both of them I can see in the registry editor. I have no idea how I missed this! I will try to get a working version using the registry uninstall path ASAP but will keep the start menu way as a fallback method in case the registry method doesn't work.

EDIT: lol I've assigned myself to this

**Comment by BanCrash** [comment]
Glad to read that!

By the way, this will solve also the other issue. In uninstall string it shows the real riotclientServices.exe path.

![image](https://user-images.githubusercontent.com/11770760/85201689-b1599a00-b301-11ea-84a8-e6348d344b50.png)

**Comment by urwrstkn8mare** [comment]
Yeah, I was just thinking that. This means I could have the plugin automatically detect the RiotClientServices.exe path as well! Unfortunately, it looks like it can automatically detect only if a game is already installed so I'll keep the old functionality for manual configuration. I would also be able to make the uninstall button go straight to the uninstaller instead of taking the user to the Programs and Features window. This looks promising!!

**Comment by urwrstkn8mare** [comment]
Ok, I've finished! I've changed the plugin to use the registry in [v0.2.0](https://github.com/urwrstkn8mare/galaxy-riot-integration/releases)! Thanks @BanCrash for that information I had no idea! Unfortunately, @BtencateSphereon, you must still enable shortcuts when installing the games. However, you can still delete both the desktop shortcuts and start menu shortcuts after. (Learn More: #6)

To find out more about the new version check out the [release](https://github.com/urwrstkn8mare/galaxy-riot-integration/releases/tag/v0.2.0) and look at the info underneath.
